package com.trueland.ecerp.domain;

// Generated 2013-6-27 23:34:30 by Hibernate Tools 3.4.0.CR1

/**
 * EcerpProduct generated by hbm2java
 */
public class EcerpProduct implements java.io.Serializable {

    private Integer id;
    private String name;
    private Double cost;
    private Double price;
    private Integer storage;
    private String brandName;
    private Integer brandId;
    private String productTypeName;
    private Integer productTypeId;

    public EcerpProduct() {
    }

    public EcerpProduct(String name, Double cost, Double price,
            Integer storage, String brandName, Integer brandId,
            String productTypeName, Integer productTypeId) {
        this.name = name;
        this.cost = cost;
        this.price = price;
        this.storage = storage;
        this.brandName = brandName;
        this.brandId = brandId;
        this.productTypeName = productTypeName;
        this.productTypeId = productTypeId;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Double getCost() {
        return this.cost;
    }

    public void setCost(Double cost) {
        this.cost = cost;
    }

    public Double getPrice() {
        return this.price;
    }

    public void setPrice(Double price) {
        this.price = price;
    }

    public Integer getStorage() {
        return this.storage;
    }

    public void setStorage(Integer storage) {
        this.storage = storage;
    }

    public String getBrandName() {
        return this.brandName;
    }

    public void setBrandName(String brandName) {
        this.brandName = brandName;
    }

    public Integer getBrandId() {
        return this.brandId;
    }

    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    public String getProductTypeName() {
        return this.productTypeName;
    }

    public void setProductTypeName(String productTypeName) {
        this.productTypeName = productTypeName;
    }

    public Integer getProductTypeId() {
        return this.productTypeId;
    }

    public void setProductTypeId(Integer productTypeId) {
        this.productTypeId = productTypeId;
    }

}
